services:
  db:
    image: postgres:16
    container_name: cloudshare-db
    environment:
      POSTGRES_DB: fileshare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: cloudshare-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudshare-backend
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-default}
      SPRING_DATASOURCE_URL: ${DOCKER_SPRING_DATASOURCE_URL:-jdbc:postgresql://db:5432/fileshare}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${DOCKER_SPRING_DATASOURCE_DRIVER_CLASS_NAME:-org.postgresql.Driver}
      SPRING_DATASOURCE_USERNAME: ${DOCKER_SPRING_DATASOURCE_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DOCKER_SPRING_DATASOURCE_PASSWORD:-postgres}
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_AWS_S3_BUCKET: ${APP_AWS_S3_BUCKET}
      APP_AWS_ACCESS_KEY: ${APP_AWS_ACCESS_KEY}
      APP_AWS_SECRET_KEY: ${APP_AWS_SECRET_KEY}
      APP_AWS_REGION: ${APP_AWS_REGION}
      APP_PUBLIC_BASE_URL: http://localhost:8080
      APP_VERIFICATION_BASE_URL: http://localhost:5173
      APP_PASSWORD_RESET_BASE_URL: http://localhost:5173
      APP_CORS_ALLOWED_ORIGINS: http://localhost:5173
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_SMTP_STARTTLS_ENABLE: "true"
      APP_RATE_LIMIT_ENABLED: "true"
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: "6379"
      SPRING_DATA_REDIS_PASSWORD: ${SPRING_DATA_REDIS_PASSWORD}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8080
    container_name: cloudshare-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

  caddy:
    image: caddy:2-alpine
    container_name: cloudshare-caddy
    profiles: ["edge"]
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  pgdata:
  redisdata:
  caddy_data:
  caddy_config:
