ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN;
ALTER TABLE IF EXISTS users ALTER COLUMN email_verified SET DEFAULT TRUE;
UPDATE users SET email_verified = TRUE WHERE email_verified IS NULL;
ALTER TABLE IF EXISTS users ALTER COLUMN email_verified SET NOT NULL;

ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
UPDATE users SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
ALTER TABLE IF EXISTS users ALTER COLUMN created_at SET NOT NULL;
