package com.example.fileshare.file;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Instant;

@Entity
@Table(name = "file_objects")
public class FileObject {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private Long ownerId;

    @Column(nullable = false, length = 512)
    private String s3Key;

    @Column(nullable = false, length = 255)
    private String originalName;

    @Column(length = 120)
    private String mimeType;

    @Column(nullable = false)
    private long sizeBytes;

    @Column(nullable = false)
    private Instant createdAt = Instant.now();

    /**
     * Returns the database id of this file row.
     * This value is generated by JPA when the entity is persisted.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the database id for this file row.
     * This is typically managed by JPA and not set manually.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the owner user id for this file.
     * Access checks use this field to scope file operations.
     */
    public Long getOwnerId() {
        return ownerId;
    }

    /**
     * Sets the owner user id for this file.
     * The service assigns this before saving metadata.
     */
    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * Returns the S3 object key for this file.
     * This key is used to locate the object in storage.
     */
    public String getS3Key() {
        return s3Key;
    }

    /**
     * Sets the S3 object key for this file.
     * The key should point to the owner-scoped storage path.
     */
    public void setS3Key(String s3Key) {
        this.s3Key = s3Key;
    }

    /**
     * Returns the original filename provided by the client.
     * This name is shown back in API responses.
     */
    public String getOriginalName() {
        return originalName;
    }

    /**
     * Sets the original filename for display and download labeling.
     * The storage key is handled separately from this field.
     */
    public void setOriginalName(String originalName) {
        this.originalName = originalName;
    }

    /**
     * Returns the MIME type associated with the uploaded file.
     * This is used when serving downloads.
     */
    public String getMimeType() {
        return mimeType;
    }

    /**
     * Sets the MIME type for this file metadata record.
     * It may be null when unknown.
     */
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    /**
     * Returns the file size in bytes.
     * This value is stored with the metadata row.
     */
    public long getSizeBytes() {
        return sizeBytes;
    }

    /**
     * Sets the file size in bytes.
     * The value is captured from upload metadata.
     */
    public void setSizeBytes(long sizeBytes) {
        this.sizeBytes = sizeBytes;
    }

    /**
     * Returns the timestamp when the file row was created.
     * New entities default this value to the current instant.
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the creation timestamp for this file row.
     * This can be used for migrations or manual entity updates.
     */
    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }
}
